Remove local files from git, add them to gitignore and WIP product infrastructure
stefanROker/FirstJavaApp pull request #1
Opened 2022-11-17 23:16 UTC by iAndu

Still not decided if ModelMapper is better than MapStruct or not.

2022-11-19 13:13 UTC, stefanROker requested changes

2022-11-19 17:21 UTC, iAndu commented on src/main/java/com/example/demo/service/ProductService.java
> +        product.setId(0L);
The way I've learned this is that if someone spoofs the request from front end and adds an existing ID to a create request you may end up doing an update instead, so call it defensive coding until I learn how to do validations.
I suppose there is a Jackson annotation that instructs to ignore a field if present in requests, such as ID in order not to populate that ever, but even then we still need to make sure to set the ID to 0 (in case of create), either by default value or by setting it here.

2022-11-19 17:21 UTC, iAndu commented on src/main/java/com/example/demo/controller/ProductController.java
> +        Product product = productService.getProduct(id);
Raised https://projecturus.atlassian.net/browse/PU-18?atlOrigin=eyJpIjoiNDcyZjQ4NTZmN2EyNDQxZWFiZWE1NTQyOTc0ZDg1YjIiLCJwIjoiaiJ9 to track this feeature.

2022-11-19 19:51 UTC, iAndu commented on src/main/java/com/example/demo/service/ProductService.java
> +        return productEntity.isPresent() ? modelMapper.map(productEntity, Product.class) : null;
Added exception handler.

2022-11-19 19:52 UTC, iAndu commented on src/main/java/com/example/demo/service/ProductService.java
> +        product.setId(0L);
I removed this after ignoring it at deserialization and it works like a charm.

2022-11-20 11:50 UTC, stefanROker commented on pom.xml
> -<!--            <artifactId>spring-boot-starter-security</artifactId>-->
Ye

2022-11-20 11:52 UTC, stefanROker commented on src/main/java/com/example/demo/model/Product.java
> +    private Long id = 0L;
Theoretically this is the Request that it's coming from the FE, so we shouldn't construct any in code, and it should be validated when coming. If we create one in code it means we are doing something wrong, or if we want to use it as some kind of response, we will have another Model class for the response, as it could differ by data that it aggregates by the same principle we talked about in the Req vs Entity earlier

2022-11-20 11:52 UTC, stefanROker commented on src/main/java/com/example/demo/service/ProductService.java
> +        return productEntity.isPresent() ? modelMapper.map(productEntity, Product.class) : null;
Cannot see it? Did you push the commits.

2022-11-20 11:58 UTC, stefanROker commented on src/main/java/com/example/demo/model/Product.java
> +    private Integer quantity = 0;
I'm not sure we need the no-args constructor anywhere. If that's the case, we don't care about not having values since we have @RequiredArgs from @Data that does it for us. Pre-initialized data that wasn't set at construction of the object means we dont really need the field, so we don't care of it's value, and whatever @Requiredargs puts there is good enough. 
That's my 2 cents though, maybe im wrong. Il look to see if there are any best practices related to this or possible problems.

2022-11-20 19:51 UTC, iAndu commented on src/main/java/com/example/demo/service/ProductService.java
> +        return productEntity.isPresent() ? modelMapper.map(productEntity, Product.class) : null;
Yeah, forgot to push it. You can see it now in the `exception` package.

2022-11-20 19:53 UTC, iAndu commented on pom.xml
> -<!--            <artifactId>spring-boot-starter-security</artifactId>-->
Done.

2022-11-20 19:54 UTC, iAndu commented on src/main/java/com/example/demo/service/ProductService.java
> +        return productEntity.isPresent() ? modelMapper.map(productEntity, Product.class) : null;
Removed the initialization.

2022-11-20 19:54 UTC, iAndu commented on src/main/java/com/example/demo/model/Product.java
> +    private Integer quantity = 0;
Removed the initialization.

2022-11-20 19:54 UTC, iAndu commented on src/main/java/com/example/demo/model/Product.java
> +    private Long id = 0L;
Removed the initialization.

2022-11-26 19:43 UTC, stefanROker approved these changes

2022-11-26 20:07 UTC, merged